Repository ThePorgs/Exegol-images, pull requests merged in 2023-08, with the labels that each got.

#194 Preparing for the next release
  .github/workflows/sub_test.yml
  sources/assets/exegol/build_pipeline_tests/run_tests.py
  sources/assets/zsh/aliases.d/Xspear
  sources/assets/zsh/aliases.d/bqm
  sources/assets/zsh/aliases.d/brakeman
  sources/assets/zsh/aliases.d/burpsuite
  sources/assets/zsh/aliases.d/cewl
  sources/assets/zsh/aliases.d/evil-winrm
  sources/assets/zsh/aliases.d/haiti
  sources/assets/zsh/aliases.d/msfconsole
  sources/assets/zsh/aliases.d/pass-station
  sources/assets/zsh/aliases.d/timing_attack
  sources/assets/zsh/aliases.d/tls-map
  sources/assets/zsh/aliases.d/whatweb
  sources/assets/zsh/aliases.d/wpscan
  sources/assets/zsh/aliases.d/ysoserial
  sources/assets/zsh/aliases.d/zsteg
  sources/assets/zsh/history.d/gf
  sources/assets/zsh/zshrc
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_iot.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_most_used.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
Labels: new tool(s), ready for merge, bugfix

#195 Sqlmap (latest) install from git
  sources/install/package_most_used.sh
  sources/install/package_web.sh
Labels: enhancement

#197 Fix binding and update fzf
  sources/install/package_base.sh
  sources/install/package_c2.sh
Labels: ready for merge, bugfix

#206 Refactoring tools lists export workflow
  .github/workflows/entrypoint_nightly.yml
  .github/workflows/entrypoint_preprod_ad.yml
  .github/workflows/entrypoint_preprod_full.yml
  .github/workflows/entrypoint_preprod_light.yml
  .github/workflows/entrypoint_preprod_osint.yml
  .github/workflows/entrypoint_preprod_web.yml
  .github/workflows/sub_build.yml
  .github/workflows/sub_build_belt.yml
  .github/workflows/sub_export_tools.yml
Labels: documentation, enhancement

#211 Remove zsh color for comments
  sources/assets/zsh/zshrc
Labels: enhancement

#212 Release 3.1.1
  .github/workflows/entrypoint_pull_request.yml
  sources/assets/bloodhound/customqueries.json
  sources/assets/zsh/zshrc
  sources/install/package_ad.sh
Labels: enhancement

#214 Add code compliance checks
  .github/workflows/entrypoint_nightly.yml
  .github/workflows/entrypoint_preprod_ad.yml
  .github/workflows/entrypoint_preprod_full.yml
  .github/workflows/entrypoint_preprod_light.yml
  .github/workflows/entrypoint_preprod_osint.yml
  .github/workflows/entrypoint_preprod_web.yml
  .github/workflows/entrypoint_pull_request.yml
  .github/workflows/sub_code_check.yml
  Dockerfile
  ad.dockerfile
  debug.dockerfile
  light.dockerfile
  osint.dockerfile
  sources/assets/zsh/aliases.d/bat
  sources/assets/zsh/aliases.d/clusterd
  sources/code_compliance_check.py
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_desktop.sh
  sources/install/package_forensic.sh
  sources/install/package_iot.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_most_used.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
  web.dockerfile
Labels: enhancement

#204 neovim
  sources/assets/exegol/load_supported_setups.sh
  sources/install/package_base.sh
Labels: new tool(s)

#219 load_supported_setups: expand aliases to fix bug #207
  sources/assets/exegol/load_supported_setups.sh
Labels: bugfix
