Repository ThePorgs/Exegol-images, pull requests merged in 2023-09, with the labels that each got.

#225 Change of Crackmapexec repo
  sources/install/package_ad.sh
Labels: bugfix

#224 fix: install zsh before changing shell
  sources/install/package_base.sh
Labels: bugfix

#226 Warning : PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set
  sources/install/common.sh
  sources/install/package_base.sh
Labels: bugfix

#232 Fix/pwntools
  sources/install/package_reverse.sh
Labels: bugfix

#230 Switch to uppercase bash variables
  sources/assets/exegol/entrypoint.sh
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/exegol/start.sh
  sources/install/package_ad.sh
  sources/install/package_base.sh
Labels: enhancement, ready for merge

#229 Fix pwncat-cs warning - Blowfish has been deprecated
  sources/install/package_c2.sh
Labels: bugfix

#231 Add a listening process check at the end of the build
  sources/install/package_base.sh
Labels: enhancement

#228 Add the tool RustScan
  sources/assets/zsh/history.d/rustscan
  sources/install/package_network.sh
Labels: new tool(s)

#221 New tools - August 2023
  sources/assets/zsh/aliases.d/MurMurHash
  sources/assets/zsh/aliases.d/blackbird
  sources/assets/zsh/aliases.d/geopincer
  sources/assets/zsh/aliases.d/pyftpdlib
  sources/assets/zsh/aliases.d/sherlock
  sources/assets/zsh/aliases.d/teamsphisher
  sources/assets/zsh/history
  sources/assets/zsh/history.d/MurMurHash
  sources/assets/zsh/history.d/azure-cli
  sources/assets/zsh/history.d/blackbird
  sources/assets/zsh/history.d/censys
  sources/assets/zsh/history.d/chainsaw
  sources/assets/zsh/history.d/geopincer
  sources/assets/zsh/history.d/gomapenum
  sources/assets/zsh/history.d/pp-finder
  sources/assets/zsh/history.d/rsacracker
  sources/assets/zsh/history.d/sherlock
  sources/assets/zsh/history.d/teamsphisher
  sources/assets/zsh/history.d/yalis
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_misc.sh
  sources/install/package_osint.sh
Labels: new tool(s)

#233 Merge configure function into install function
  Dockerfile
  ad.dockerfile
  light.dockerfile
  osint.dockerfile
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cracking.sh
  sources/install/package_misc.sh
  sources/install/package_osint.sh
  sources/install/package_web.sh
  sources/install/package_wordlists.sh
  web.dockerfile
Labels: enhancement

#236 attempting to fix trilium unit test timeout
  sources/assets/exegol/build_pipeline_tests/run_tests.py
  sources/assets/trilium/document.db
  sources/assets/trilium/document.db-shm
  sources/assets/trilium/document.db-wal
  sources/assets/trilium/trilium-manager.sh
  sources/assets/zsh/aliases.d/trilium
  sources/install/package_misc.sh
Labels: enhancement, ready for merge

#237 Use port 80 to connect to gpg keyservers
  sources/install/package_base.sh
Labels: enhancement, ready for merge

#238 Attempting to fix random network issues when building
  debug.dockerfile
  sources/assets/exegol/load_supported_setups.sh
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
Labels: enhancement, ready for merge

#240 fix typo in proxmark
  sources/install/package_rfid.sh
Labels: ready for merge, bugfix

#241 temp fix proxmark3
  sources/install/package_rfid.sh
Labels: bugfix

#239 Mini refacto, cleaning useless functions
  sources/assets/zsh/history.d/msfconsole
  sources/install/common.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
Labels: ready for merge

#244 New tools and fixes - September 2023
  sources/assets/netexec/nxc.conf
  sources/assets/zsh/aliases.d/GPOddity
  sources/assets/zsh/aliases.d/extractbitlockerkeys
  sources/assets/zsh/aliases.d/netexec
  sources/assets/zsh/history.d/GPOddity
  sources/assets/zsh/history.d/extractbitlockerkeys
  sources/assets/zsh/history.d/netexec
  sources/code_compliance_check.py
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_iot.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_most_used.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
Labels: new tool(s), ready for merge, bugfix

#186 add mobsf to mobile packages
  sources/assets/zsh/aliases.d/mobsf
  sources/assets/zsh/history.d/mobsf
  sources/install/package_mobile.sh
Labels: new tool(s), ready for merge

#245 Fix load supported setups
  sources/assets/exegol/load_supported_setups.sh
Labels: ready for merge, bugfix

#247 Master runcommand file for all shells
  sources/assets/bash/bashrc
  sources/assets/exegol/exegol_shells_rc
  sources/assets/zsh/zshrc
  sources/install/package_base.sh
  sources/install/package_wordlists.sh
Labels: enhancement, ready for merge

#248 nmap-parse-output
  sources/assets/zsh/history.d/nmap-parse-output
  sources/install/package_network.sh
Labels: new tool(s), ready for merge

#249 Refacto pip installs CNR
  .github/workflows/entrypoint_pr.yml
  sources/install/package_ad.sh
  sources/install/package_cloud.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
Labels: enhancement

#246 Updated firefox addon installer
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/firefox/requirements.txt
  sources/assets/firefox/setup.py
  sources/assets/firefox/user-setup.py
Labels: enhancement

#251 load_supported_setups: fix bqm not found, and BloodHound customqueries
  sources/assets/exegol/load_supported_setups.sh
Labels: bugfix
