Repository ThePorgs/Exegol-images, pull requests merged in 2023-02, with the labels that each got.

#75 New tools and bug fixes
  sources/install.sh
  sources/zsh/aliases.d/php_filter_chain_generator
  sources/zsh/aliases.d/tailscale
  sources/zsh/aliases.d/volatility
  sources/zsh/aliases.d/volatility2
  sources/zsh/aliases.d/volatility3
  sources/zsh/history.d/brakeman
  sources/zsh/history.d/dnsx
  sources/zsh/history.d/exif
  sources/zsh/history.d/exiv2
  sources/zsh/history.d/fdisk
  sources/zsh/history.d/hexedit
  sources/zsh/history.d/jadx
  sources/zsh/history.d/objection
  sources/zsh/history.d/semgrep
  sources/zsh/history.d/shuffledns
  sources/zsh/history.d/subfinder
  sources/zsh/history.d/swaks
  sources/zsh/history.d/tailscale
  sources/zsh/history.d/testdisk
  sources/zsh/history.d/volatility3
Labels: enhancement, new tool(s), ready for merge

#98 Fixing google chrome installation
  sources/install.sh
Labels: ready for merge

#87 Adding smuggler.py
  sources/install.sh
  sources/zsh/aliases.d/smuggler
  sources/zsh/history.d/smuggler
Labels: new tool(s), ready for merge

#103 add ctf-party
  sources/install.sh
  sources/zsh/history.d/ctf-party
Labels: new tool(s)

#102 add haiti
  sources/install.sh
  sources/zsh/history.d/haiti
Labels: new tool(s)

#105 add tls map
  sources/install.sh
  sources/zsh/history.d/tls-map
Labels: new tool(s)

#108 Troubleshooting kerbrute installation (AMD + ARM)
  sources/install.sh
Labels: enhancement, arm64

#107 Adding customization for firefox
  sources/firefox/places.sqlite
  sources/firefox/requirements.txt
  sources/firefox/setup.py
  sources/install.sh
Labels: enhancement, ready for merge
