Repository ThePorgs/Exegol-images, pull requests merged in 2023-11, with the labels that each got.

#274 Add some Bloodhound custom queries
  sources/assets/bloodhound/customqueries.json
Labels: enhancement

#275 Shell scripts alignment
  sources/assets/burpsuite/trust-ca-burp.sh
  sources/assets/exegol/entrypoint.sh
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/exegol/start.sh
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_desktop.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_web.sh
  sources/install/package_wordlists.sh
Labels: enhancement

#276 fix: allow the shell to split arguments to kill
  sources/install/package_base.sh
Labels: bugfix

#279 fix(ad): extend temp fix for gmsadumper
  sources/install/package_ad.sh
Labels: ready for merge
