Repository ThePorgs/Exegol-images, pull requests merged in 2023-06, with the labels that each got.

#164 Fix/bugs - Discord Tickets
  sources/assets/zsh/aliases.d/checksec
  sources/assets/zsh/aliases.d/pth-tools
  sources/assets/zsh/history.d/checksec
  sources/assets/zsh/history.d/objectwalker
  sources/assets/zsh/history.d/sliver
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_misc.sh
  sources/install/package_reverse.sh
  sources/install/package_web.sh
Labels: new tool(s), ready for merge, bugfix

#162 Add noPac: Exploiting CVE-2021-42278 and CVE-2021-42287 to impersonat…
  sources/assets/zsh/aliases.d/noPac
  sources/assets/zsh/history.d/crackmapexec
  sources/assets/zsh/history.d/noPac
  sources/install/package_ad.sh
Labels: new tool(s)

#160 Add commands to zsh history
  sources/assets/zsh/history.d/certipy
  sources/assets/zsh/history.d/impacket
  sources/assets/zsh/history.d/krbrelayx
  sources/assets/zsh/history.d/pkinittools
  sources/assets/zsh/history.d/rusthound
  sources/assets/zsh/history.d/xfreerdp
Labels: enhancement, ready for merge

#139 New tool - Rsactftool
  sources/assets/zsh/aliases.d/rsactftool
  sources/assets/zsh/history.d/rsactftool
  sources/install/package_crypto.sh
Labels: new tool(s), on hold

#167 Fix variable in bloodhound custom query
  sources/assets/bloodhound/customqueries.json
Labels: bugfix

#141 🎉 Remote Graphical Desktop 🎉
  sources/assets/guacamole/bin/desktop-restart
  sources/assets/guacamole/bin/desktop-start
  sources/assets/guacamole/bin/desktop-stop
  sources/assets/guacamole/custom-css/images/logo-144.png
  sources/assets/guacamole/custom-css/images/logo-64.png
  sources/assets/guacamole/custom-css/images/logo.png
  sources/assets/guacamole/custom-css/theme.css
  sources/assets/guacamole/etc-srv/guacamole.properties
  sources/assets/guacamole/etc-srv/user-mapping.xml
  sources/assets/guacamole/kdeglobals
  sources/assets/guacamole/wallpaper.png
  sources/install/guacamole_install.sh
  sources/install/package_base.sh
Labels: enhancement, ready for merge

#169 Fixed installation of some tools
  sources/assets/zsh/aliases.d/eaphammer
  sources/assets/zsh/aliases.d/patator
  sources/assets/zsh/aliases.d/xsser
  sources/assets/zsh/history.d/eaphammer
  sources/assets/zsh/history.d/ignorant
  sources/assets/zsh/history.d/osrframework
  sources/assets/zsh/history.d/patator
  sources/assets/zsh/history.d/recon-ng
  sources/assets/zsh/history.d/whois
  sources/assets/zsh/history.d/xsser
  sources/install/package_ad.sh
  sources/install/package_most_used.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_web.sh
Labels: bugfix

#172 Rusthound: remove the duplicated dependency libclang-dev
  sources/install/package_ad.sh
Labels: bugfix

#171 Replace all git clone --depth=1 by --depth 1 for compliance
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_code_analysis.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
Labels: enhancement

#177 Update to the new repository of CME
  sources/assets/crackmapexec/cme.conf
  sources/install/package_ad.sh
Labels: ready for merge, bugfix
