Repository ThePorgs/Exegol-images, pull requests merged in 2023-04, with the labels that each got.

#125 Add tools description
  sources/install.sh
Labels: documentation

#145 New tool - trevorspray
  sources/assets/zsh/history.d/trevorspray
  sources/install/package_osint.sh
Labels: new tool(s), ready for merge

#146 Fix - buster
  sources/install/package_osint.sh
Labels: ready for merge, bugfix

#148 Fix - joomscan
  sources/assets/zsh/history.d/joomscan
  sources/install/package_web.sh
Labels: ready for merge, bugfix

#147 Fix - spiderfoot
  sources/assets/zsh/aliases.d/spiderfoot
  sources/install/package_osint.sh
Labels: ready for merge, bugfix

#135 Added missing dependencies for autorecon
  sources/install/package_network.sh
Labels: ready for merge, bugfix

#140 New tool - Peepdf
  sources/assets/zsh/aliases.d/peepdf
  sources/install/package_forensic.sh
Labels: new tool(s), ready for merge

#144 New tool - ligolo-ng
  sources/assets/zsh/history.d/ligolo-ng
  sources/install/package_network.sh
Labels: new tool(s), ready for merge, bugfix

#142 Fix - phpggc
  sources/install/package_web.sh
Labels: ready for merge, bugfix
