Repository ThePorgs/Exegol-images, pull requests merged in 2023-03, with the labels that each got.

#113 Pypykatz - Update minikerberos version
  sources/install.sh
Labels: enhancement

#114 Fix pywsus history command
  sources/zsh/history.d/pywsus
Labels: bugfix

#115 Add SoapUI tool
  sources/install.sh
  sources/zsh/aliases.d/soapui
Labels: new tool(s)

#116 Add Netdiscover Tool
  sources/install.sh
  sources/zsh/history.d/netdiscover
Labels: new tool(s)

#112 Update CrackMapExec to use latest version from the repo
  sources/install.sh
Labels: enhancement

#119 New tool - Notify
  sources/install.sh
  sources/zsh/history.d/notify
Labels: new tool(s)

#120 Fixed Firefox customization issue and added support for addons in my-resources
  sources/exegol/load_supported_setups.sh
  sources/exegol/skel/firefox/addons.txt
  sources/firefox/requirements.txt
  sources/firefox/setup.py
  sources/firefox/user-setup.py
  sources/install.sh
Labels: enhancement, bugfix
