Repository ThePorgs/Exegol-images, pull requests merged in 2023-07, with the labels that each got.

#182 Add zsh alias 'ws' to quickly change directory to the workspace
  sources/assets/zsh/aliases
Labels: enhancement

#184 Use pipx to install DonPAPI after they moved to pyproject.toml
  sources/assets/zsh/aliases.d/donpapi
  sources/assets/zsh/history.d/donpapi
  sources/install/package_ad.sh
Labels: enhancement

#181 Add BloodHound customqueries support to my-resources (merge/replace)
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/exegol/skel/bloodhound/README.md
  sources/assets/exegol/skel/bloodhound/customqueries_merge/README.md
  sources/assets/exegol/skel/bloodhound/customqueries_replacement/README.md
Labels: enhancement

#180 Dev Add Cloud tools (cloudsplaining, cloudsploit and prowler)
  sources/assets/zsh/aliases.d/cloudsploit
  sources/assets/zsh/history.d/cloudsplaining
  sources/assets/zsh/history.d/prowler
  sources/install/package_cloud.sh
Labels: waiting for additional changes, new tool(s)

#185 add scrcpy to mobile tools
  sources/assets/zsh/history.d/scrcpy
  sources/install/package_mobile.sh
Labels: new tool(s)

#188 Clean rusthound
  sources/install/package_ad.sh
Labels: enhancement

#187 Reduce Docker layers
  Dockerfile
  ad.dockerfile
  debug.dockerfile
  light.dockerfile
  osint.dockerfile
  web.dockerfile
Labels: enhancement

#191 Add sqlite3
  sources/install/package_base.sh
Labels: new tool(s)

#193 [my-resources] Remove any bqm temporary file for Bloodhound
  sources/assets/exegol/load_supported_setups.sh
Labels: enhancement
