Repository ThePorgs/Exegol-images, pull requests merged in 2023-10, with the labels that each got.

#253 Adding LDAPWordlistHarvester
  sources/assets/zsh/aliases.d/LDAPWordlistHarvester
  sources/assets/zsh/history.d/LDAPWordlistHarvester
  sources/install/package_ad.sh
Labels: new tool(s)

#254 Installing sslscan from source
  sources/install/package_most_used.sh
  sources/install/package_web.sh
Labels: bugfix

#257 Added an fzf-haiti command
  sources/assets/zsh/aliases.d/fzf
  sources/assets/zsh/history.d/hashcat
Labels: new tool(s)

#252 Adding cewler
  sources/assets/zsh/history.d/cewler
  sources/install/package_wordlists.sh
Labels: new tool(s)

#255 Add pywerview
  sources/assets/zsh/history.d/pywerview
  sources/install/package_ad.sh
Labels: new tool(s)

#256 Add freeipscanner
  sources/assets/zsh/history.d/freeipscanner
  sources/assets/zsh/history.d/scrtdnsdump
  sources/install/package_ad.sh
Labels: waiting for additional changes, new tool(s)

#263 Fix 7zip2john
  sources/install/package_cracking.sh
Labels: bugfix

#264 Fix/kerberos tools
  sources/install/package_ad.sh
Labels: bugfix

#262 Adding Pull Request title filter to initial release workflow
  .github/workflows/entrypoint_preprod_base.yml
Labels: enhancement

#260 Improving python installs
  sources/install/package_base.sh
  sources/install/package_osint.sh
Labels: enhancement, bugfix

#266 Updated custom query for cross domain rights.
  sources/assets/bloodhound/customqueries.json
Labels: enhancement

#267 Fixing bloodhound.py
  sources/install/package_ad.sh
Labels: ready for merge, bugfix

#123 Certs trust support in my-resources + auto trust Burp CA
  sources/assets/burpsuite/conf.json
  sources/assets/burpsuite/trust-ca-burp.sh
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/exegol/skel/supported_setups.md
  sources/assets/firefox/setup.py
  sources/install/package_base.sh
  sources/install/package_web.sh
Labels: enhancement, manual tests required, my-resources

#270 Added check on existing certs in my-resources before looping.
  sources/assets/exegol/load_supported_setups.sh
Labels: my-resources

#272 Added WHERE clause to avoid errors on query.
  sources/assets/bloodhound/customqueries.json
Labels: bugfix

#265 Add Empire
  sources/assets/shells/aliases.d/empire
  sources/assets/shells/exegol_shells_rc
  sources/assets/shells/history.d/empire
  sources/install/package_ad.sh
  sources/install/package_c2.sh
Labels: new tool(s), on hold

#259 Add CyberChef
  sources/assets/firefox/places.sqlite
  sources/install/package_base.sh
  sources/install/package_misc.sh
  sources/install/package_most_used.sh
Labels: new tool(s)

#273 Fixed typo in find command.
  sources/assets/exegol/load_supported_setups.sh
Labels: bugfix, my-resources
