Repository ThePorgs/Exegol-images, pull requests merged in 2024-10, with the labels that each got.

#386 Add custom arsenal cheatsheets feature for my resources
  sources/assets/exegol/load_supported_setups.sh
Labels: enhancement, my-resources

#393 BloodHound: Add a new query to list users who can ReadLAPSPassword and improve other queries
  sources/assets/bloodhound/customqueries.json
Labels: enhancement

#388 Added Alias and history
  sources/assets/shells/aliases.d/networkIP
  sources/assets/shells/history.d/nmap
Labels: enhancement, ready for merge

#402 Fix bloodhound-ce collectors
  sources/install/package_ad.sh
Labels: ready for merge, bugfix

#406 Fix the pipeline
  sources/install/package_ad.sh
Labels: ready for merge, bugfix, waiting for review

#399 Add Mitmproxy
  sources/assets/shells/history.d/mitmproxy
  sources/install/package_network.sh
Labels: new tool(s), ready for merge

#403 Fix remmina installation
  sources/install/package_network.sh
Labels: ready for merge, bugfix

#404 Fix jwt_tool configuration
  sources/install/package_web.sh
Labels: ready for merge, bugfix

#382 Add WES-NG
  sources/assets/shells/history.d/wesng
  sources/install/package_misc.sh
Labels: new tool(s), ready for merge

#409 fix adminer
  sources/assets/shells/history.d/adminer
Labels: ready for merge, bugfix

#411 feat: new tool autobloody
  sources/assets/shells/history.d/autobloody
  sources/install/package_ad.sh
Labels: new tool(s), ready for merge
