Repository ThePorgs/Exegol-images, pull requests merged in 2024-06, with the labels that each got.

#350 Update uberfile history
  sources/assets/shells/history.d/uberfile
Labels: ready for merge, bugfix

#349 Add uploader
  sources/assets/shells/aliases.d/uploader
  sources/assets/shells/history.d/uploader
  sources/install/package_misc.sh
Labels: new tool(s), under review

#348 Fix binwalk dependencies
  sources/assets/shells/aliases.d/binwalk
  sources/install/package_forensic.sh
Labels: ready for merge, bugfix

#361 Fix checksec & androguard
  sources/install/package_mobile.sh
  sources/install/package_reverse.sh
Labels: ready for merge, bugfix

#362 Fix typo in a Bloodhound custom query
  sources/assets/bloodhound/customqueries.json
Labels: ready for merge, bugfix

#359 Add faketime history
  sources/assets/shells/history.d/faketime
Labels: enhancement, ready for merge

#358 Fix spiderfoot alias
  sources/assets/shells/aliases.d/spiderfoot
Labels: ready for merge, bugfix

#357 Move pyrit into the PATH
  sources/assets/shells/aliases.d/pyrit
  sources/install/package_wifi.sh
Labels: ready for merge, bugfix

#356 Added missing dependency to pwndb
  sources/install/package_osint.sh
Labels: ready for merge, bugfix

#355 Add katana tool
  sources/assets/shells/history.d/katana
  sources/install/package_web.sh
Labels: new tool(s), ready for merge

#354 Add jsluice
  sources/assets/shells/history.d/jsluice
  sources/install/package_web.sh
Labels: new tool(s), ready for merge

#351 Adding Postman to Exegol
  sources/assets/shells/history.d/postman
  sources/install/package_web.sh
Labels: new tool(s), ready for merge

#352 Add smbclient-ng
  sources/assets/shells/history.d/smbclient-ng
  sources/install/package_ad.sh
Labels: new tool(s)

#363 Replace sherlock installation from sources with pipx
  sources/assets/shells/aliases.d/sherlock
  sources/assets/shells/history.d/sherlock
  sources/install/package_osint.sh
Labels: bugfix
