Repository ThePorgs/Exegol-images, pull requests merged in 2024-11, with the labels that each got.

#414 Fix metasploit installation and CCC
  sources/code_compliance_check.py
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_desktop.sh
  sources/install/package_mobile.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
Labels: bugfix

#407 Improve Sharphound and Azurehound installations
  sources/install/package_ad.sh
Labels: ready for merge, bugfix

#419 Create owneredit history
  sources/assets/shells/history.d/impacket
Labels: enhancement, waiting for fix
