Repository ThePorgs/Exegol-images, pull requests merged in 2024-09, with the labels that each got.

#379 Reorganize impacket history
  sources/assets/shells/history.d/impacket
Labels: ready for merge

#380 Bloodhound queries: improve outdated OS and top 10 users queries and misc fixes
  sources/assets/bloodhound/customqueries.json
Labels: enhancement, ready for merge

#383 Fixed a bug allowing configuration updates following Responder update
  sources/assets/shells/aliases.d/responder
Labels: ready for merge, bugfix

#385 Modified BH customqueries to find T0 assets
  sources/assets/bloodhound/customqueries.json
Labels: enhancement, ready for merge
