Repository ThePorgs/Exegol-images, pull requests merged in 2024-05, with the labels that each got.

#343 Update nuclei to version 3
  sources/install/package_web.sh
Labels: enhancement

#342 Fix username-anarchy
  sources/install/package_wordlists.sh
Labels: bugfix, under review

#346 Release 3.1.4
  .github/workflows/sub_code_check.yml
  .github/workflows/sub_export_tools.yml
  sources/assets/desktop/applications/burpsuite.desktop
  sources/assets/shells/history.d/asrepcatcher
  sources/assets/shells/history.d/creds
  sources/assets/shells/history.d/nuclei
  sources/code_compliance_check.py
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cracking.sh
  sources/install/package_desktop.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
Labels: base success
