Repository ThePorgs/Exegol-images, pull requests merged in 2024-04, with the labels that each got.

#310 Reducing the size of venv by using common packages
  sources/assets/python/requirements.txt
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_forensic.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
Labels: enhancement

#324 Bloodhound customqueries: better RDP queries
  sources/assets/bloodhound/customqueries.json
Labels: enhancement, waiting for review

#323 New tools (and fixes) - April 2024
  sources/assets/shells/aliases.d/extractbitlockerkeys
  sources/assets/shells/aliases.d/sccmhunter
  sources/assets/shells/aliases.d/sccmwtf
  sources/assets/shells/history.d/bloodyAD
  sources/assets/shells/history.d/dploot
  sources/assets/shells/history.d/sccmhunter
  sources/assets/shells/history.d/sccmwtf
  sources/install/package_ad.sh
  sources/install/package_forensic.sh
  sources/install/package_wordlists.sh
Labels: new tool(s), bugfix, waiting for review

#330 Temp fix for Pyrit install
  sources/install/package_wifi.sh
Labels: bugfix

#318 Install and init msfdb
  sources/assets/shells/aliases.d/metasploit
  sources/install/package_c2.sh
Labels: bugfix

#319 Fix Bloodhound-ce deployment adding config file
  sources/assets/bloodhound-ce/bloodhound.config.json
  sources/install/package_ad.sh
Labels: bugfix

#328 Installing Java21 for latest BurpSuite
  sources/assets/shells/aliases.d/burpsuite
  sources/assets/shells/aliases.d/ysoserial
  sources/install/package_base.sh
  sources/install/package_rfid.sh
Labels: bugfix

#331 Release 3.1.3
  .github/workflows/entrypoint_preprod_ad.yml
  .github/workflows/entrypoint_preprod_base.yml
  .github/workflows/entrypoint_preprod_full.yml
  .github/workflows/entrypoint_preprod_light.yml
  .github/workflows/entrypoint_preprod_osint.yml
  .github/workflows/entrypoint_preprod_web.yml
  .github/workflows/sub_build.yml
  .github/workflows/sub_code_check.yml
  .github/workflows/sub_export_tools.yml
  sources/assets/bloodhound-ce/bloodhound.config.json
  sources/assets/bloodhound/customqueries.json
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/patches/openssl.patch
  sources/assets/python/requirements.txt
  sources/assets/shells/aliases.d/_init
  sources/assets/shells/aliases.d/burpsuite
  sources/assets/shells/aliases.d/evil-winrm
  sources/assets/shells/aliases.d/extractbitlockerkeys
  sources/assets/shells/aliases.d/metasploit
  sources/assets/shells/aliases.d/responder
  sources/assets/shells/aliases.d/sccmhunter
  sources/assets/shells/aliases.d/sccmwtf
  sources/assets/shells/aliases.d/ysoserial
  sources/assets/shells/history.d/abuseACL
  sources/assets/shells/history.d/bloodyAD
  sources/assets/shells/history.d/certipy
  sources/assets/shells/history.d/crackmapexec
  sources/assets/shells/history.d/dploot
  sources/assets/shells/history.d/kerbrute
  sources/assets/shells/history.d/netexec
  sources/assets/shells/history.d/pretender
  sources/assets/shells/history.d/responder
  sources/assets/shells/history.d/sccmhunter
  sources/assets/shells/history.d/sccmwtf
  sources/assets/shells/history.d/ssh-audit
  sources/assets/shells/zshrc
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_desktop.sh
  sources/install/package_forensic.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
  wifi.dockerfile
Labels: base success

#321 Adding tool ASRepCatcher
  sources/assets/shells/history.d/asrepcatcher
  sources/install/package_ad.sh
Labels: new tool(s), ready for merge

#327 New tool creds
  sources/assets/shells/history.d/creds
  sources/install/package_misc.sh
Labels: new tool(s), ready for merge

#335 Improve CCC adding temp-fix check
  .github/workflows/sub_code_check.yml
  sources/code_compliance_check.py
  sources/install/package_mobile.sh
Labels: enhancement, ready for merge

#333 Reduce image size by adding flag depth 1 when git cloning
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cracking.sh
  sources/install/package_desktop.sh
  sources/install/package_mobile.sh
  sources/install/package_wifi.sh
Labels: enhancement, ready for merge

#336 Export of the tools list in separate files depending on the architecture
  .github/workflows/sub_export_tools.yml
Labels: documentation, enhancement

#337 Add missing dep to metasploit
  sources/install/package_c2.sh
Labels: ready for merge, bugfix

#338 Remove commas from descriptions + fix pipeline
  .github/workflows/sub_export_tools.yml
  sources/install/package_ad.sh
  sources/install/package_misc.sh
Labels: bugfix

#334 Reduce image size by removing sslscan build files
  sources/install/package_web.sh
Labels: enhancement

#340 Update nuclei history
  sources/assets/shells/history.d/nuclei
Labels: enhancement, under review
