Repository ThePorgs/Exegol-images, pull requests merged in 2024-02, with the labels that each got.

#295 Adding pretender to Exegol-Images
  sources/assets/shells/history.d/pretender
  sources/install/package_ad.sh
Labels: new tool(s), ready for merge

#292 fix: change temurin11 url
  sources/install/package_base.sh
Labels: bugfix

#300 Fix checksec-py lief version
  sources/install/package_ad.sh
  sources/install/package_mobile.sh
  sources/install/package_reverse.sh
Labels: ready for merge, bugfix

#301 Add systemctl alias
  sources/assets/shells/aliases.d/_init
Labels: enhancement, ready for merge

#304 Downgrade ruby version for evil-winrm (3.2.2 to 3.2.1)
  sources/assets/shells/aliases.d/evil-winrm
  sources/install/package_ad.sh
Labels: bugfix, waiting for review

#297 Fix Tmux parse issues when conf is created on Windows.
  sources/assets/exegol/load_supported_setups.sh
Labels: bugfix, waiting for review

#305 Get latest cyberchef release
  sources/install/package_misc.sh
Labels: bugfix

#308 OpenSSL activate legacy support
  sources/assets/patches/openssl.patch
  sources/install/package_base.sh
Labels: bugfix

#309 Remove temp fix (pycryptodome)
  sources/install/package_ad.sh
  sources/install/package_forensic.sh
Labels: bugfix

#314 TERM variable added to zshrc file for tmux compatibility
  sources/assets/shells/zshrc
Labels: bugfix

#313 Fixing masky description
  sources/install/package_ad.sh
Labels: documentation

#315 Update BHQ queries
  sources/assets/bloodhound/customqueries.json
Labels: enhancement
