Repository ThePorgs/Exegol-images, pull requests merged in 2025-09, with the labels that each got.

#544 feat: added 2 new bookmark
  sources/assets/firefox/policies.json.template
Labels: enhancement, ready for merge

#538 Add Caido
  sources/assets/shells/history.d/caido
  sources/install/package_web.sh
Labels: new tool(s), ready for merge

#487 Added glow and fzf-thr
  sources/assets/shells/aliases.d/fzf
  sources/assets/shells/aliases.d/thr
  sources/install/package_misc.sh
Labels: new tool(s)

#498 feat: replace pwncat-cs with my maintained fork pwncat-vl
  sources/assets/shells/history.d/pwncat
  sources/install/package_c2.sh
Labels: new tool(s)
