Repository ThePorgs/Exegol-images, pull requests merged in 2025-02, with the labels that each got.

#431 Fixed Gowitness history arguments
  sources/assets/shells/history.d/gowitness
Labels: enhancement

#325 Firefox policy
  sources/assets/burpsuite/trust-ca-burp.sh
  sources/assets/exegol/load_supported_setups.sh
  sources/assets/firefox/generate_policy.py
  sources/assets/firefox/policies.json.template
  sources/assets/firefox/requirements.txt
  sources/install/package_base.sh
Labels: enhancement, ready for merge

#424 Add new tool : UDPX
  sources/assets/shells/history.d/udpx
  sources/install/package_network.sh
Labels: new tool(s), ready for merge

#435 Added a -p argument to the mkdir in the Cyberchef install
  sources/install/package_misc.sh
Labels: ready for merge, bugfix

#436 Added the PEASS Ruby module for MSF
  sources/install/package_c2.sh
Labels: new tool(s), ready for merge

#428 fix(ad): rename roadtools to roadrecon and add roadtx
  sources/install/package_ad.sh
Labels: enhancement, new tool(s), ready for merge

#417 feat: add zaproxy package
  sources/assets/shells/aliases.d/zaproxy
  sources/assets/shells/history.d/zaproxy
  sources/install/package_web.sh
Labels: new tool(s), ready for merge

#446 Add missing sha256 sum - Bloodhound-CE
  sources/install/package_ad.sh
Labels: bugfix

#442 New tools for the light image.
  sources/install/package_most_used.sh
Labels: enhancement

#441 Fix PATH order
  sources/assets/shells/exegol_shells_rc
  sources/assets/shells/zshrc
Labels: bugfix

#440 Add proxychains to light
  sources/install/package_most_used.sh
Labels: enhancement

#439 New tools - yq / xq
  sources/install/package_misc.sh
Labels: new tool(s)

#437 Fix internal tickets
  sources/assets/shells/history.d/faketime
  sources/assets/shells/history.d/impacket
  sources/assets/shells/history.d/kerberos
  sources/install/package_ad.sh
Labels: bugfix

#443 Call post_install for each docker layer.
  .github/workflows/entrypoint_preprod_base.yml
  Dockerfile
  ad.dockerfile
  light.dockerfile
  osint.dockerfile
  sources/dockerfiles/Dockerfile
  sources/dockerfiles/ad.dockerfile
  sources/dockerfiles/base.dockerfile
  sources/dockerfiles/light.dockerfile
  sources/dockerfiles/osint.dockerfile
  sources/dockerfiles/web.dockerfile
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_base.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_desktop.sh
  sources/install/package_forensic.sh
  sources/install/package_iot.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_most_used.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
  web.dockerfile
  wifi.dockerfile
Labels: enhancement
