Repository ThePorgs/Exegol-images, pull requests merged in 2025-05, with the labels that each got.

#479 New Tool: pysnaffler
  sources/assets/shells/history.d/pysnaffler
  sources/install/package_ad.sh
Labels: new tool(s)

#496 New tool : Powerview.py
  sources/assets/shells/history.d/powerview.py
  sources/install/package_ad.sh
Labels: new tool(s)

#515 Replace apply with set + add unset command in exegol-history
  sources/assets/shells/history.d/exegol-history
Labels: bugfix

#508 Add the tool RemoteMonologue
  sources/assets/shells/aliases.d/remotemonologue
  sources/assets/shells/history.d/remotemonologue
  sources/install/package_ad.sh
Labels: new tool(s)

#485 perf: no more useless build dependencies
  sources/install/package_misc.sh
  sources/install/package_osint.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
Labels: enhancement
