Repository ThePorgs/Exegol-images, pull requests merged in 2025-03, with the labels that each got.

#456 perf: only apt-get update when needed
  sources/install/common.sh
  sources/install/package_ad.sh
  sources/install/package_c2.sh
  sources/install/package_cloud.sh
  sources/install/package_code_analysis.sh
  sources/install/package_cracking.sh
  sources/install/package_crypto.sh
  sources/install/package_desktop.sh
  sources/install/package_forensic.sh
  sources/install/package_iot.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_most_used.sh
  sources/install/package_network.sh
  sources/install/package_osint.sh
  sources/install/package_reverse.sh
  sources/install/package_rfid.sh
  sources/install/package_sdr.sh
  sources/install/package_steganography.sh
  sources/install/package_voip.sh
  sources/install/package_web.sh
  sources/install/package_wifi.sh
  sources/install/package_wordlists.sh
Labels: enhancement

#448 perf: purge cache between layers
  sources/install/common.sh
Labels: enhancement, ready for merge

#449 perf: missing git shallow
  sources/install/package_c2.sh
  sources/install/package_sdr.sh
  sources/install/package_web.sh
Labels: enhancement, ready for merge

#453 perf: useless `apt-get update` layers
  sources/dockerfiles/Dockerfile
  sources/dockerfiles/ad.dockerfile
  sources/dockerfiles/light.dockerfile
  sources/dockerfiles/osint.dockerfile
  sources/dockerfiles/web.dockerfile
Labels: enhancement, ready for merge

#455 chore: move test sort in `run_tests.py`
  .github/workflows/sub_test.yml
  sources/assets/exegol/build_pipeline_tests/run_tests.py
Labels: enhancement, ready for merge

#457 BH customqueries: fix queries based on shortestPath
  sources/assets/bloodhound/customqueries.json
Labels: ready for merge, bugfix

#460 fix: pyFindUncommonShares was renamed
  sources/assets/shells/aliases.d/finduncommonshares
  sources/install/package_ad.sh
Labels: bugfix

#429 Exegol-history v2
  sources/assets/shells/aliases.d/exegol-history
  sources/assets/shells/history.d/exegol-history
  sources/assets/shells/zshrc
  sources/install/package_base.sh
Labels: enhancement, new tool(s)

#466 Fix history
  sources/assets/shells/aliases.d/exegol-history
  sources/assets/shells/zshrc
Labels: enhancement

#465 Increasing the timeout threshold
  sources/assets/exegol/build_pipeline_tests/run_tests.py
Labels: enhancement

#464 Using higher Go version for bettercap install
  sources/assets/shells/aliases.d/bettercap
  sources/install/package_wifi.sh
Labels: bugfix

#394 Add wordlist symlinks, fzf-rules aliase and hashcat rules
  sources/assets/shells/aliases.d/fzf
  sources/install/package_base.sh
  sources/install/package_forensic.sh
  sources/install/package_wordlists.sh
Labels: enhancement

#467 Upgrading Trilium to TriliumNext and fixing seclists install
  sources/assets/shells/aliases.d/ntlmv1-multi
  sources/assets/shells/aliases.d/trilium
  sources/assets/shells/aliases.d/triliumnext
  sources/assets/shells/history.d/trilium
  sources/assets/shells/history.d/triliumnext
  sources/assets/trilium/config.ini
  sources/assets/triliumnext/config.ini
  sources/assets/triliumnext/triliumnext-manager.sh
  sources/install/package_ad.sh
  sources/install/package_misc.sh
  sources/install/package_mobile.sh
  sources/install/package_wordlists.sh
Labels: bugfix

#471 ohmyzsh git plugin
  sources/assets/shells/zshrc
Labels: enhancement

#472 Secret finders
  sources/assets/shells/history.d/gitleaks
  sources/assets/shells/history.d/trufflehog
  sources/install/package_code_analysis.sh
Labels: new tool(s)

#477 Rollback on CI auto and manual builds
  .github/workflows/entrypoint_nightly.yml
Labels: bugfix
